site_name: Zvorky's Pages
site_url: https://zvorky.github.io/

theme:
  name: material
  custom_dir: overrides
  language: en
  features:
    - navigation.tabs
    - navigation.sections
    - search.suggest
    - search.highlight
  font:
    text: Jost
    code: Atkinson Hyperlegible Mono
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Alternar para tema claro
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: red
      accent: red
      toggle:
        icon: material/brightness-7
        name: Alternar para tema escuro
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/brightness-4
        name: Alternar para preferência do sistema

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search
  - macros:
      module_name: macros
  - i18n:
      docs_structure: folder
      languages:
        - locale: en
          default: true
          name: English
        - locale: pt
          name: Português

copyright: |
  &copy; 2026 Enzo Zavorski Delevatti. <br>
  All written content on this site is licensed under the
  <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank" rel="noopener">CC BY 4.0</a>.
